version: "3.7"
services:
  mysql:
    container_name: mysql
    # image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3305:3306"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mysqlvol:/var/lib/mysql
      # - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - mysql-compose-network
volumes:
  mysqlvol: {}
networks: 
  mysql-compose-network:
    driver: bridge    